version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_DB_SCHEMA: public

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - app_network

  postgres_keycloak:
    container_name: postgres_keycloak
    image: postgres:15.2
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    healthcheck:
      test: "exit 0"
    ports:
      - "5435:5432"
    networks:
      - app_network

volumes:
  pgdata_keycloak:

networks:
  app_network:
    name: app_network
    driver: bridge